from .Inmueble import Inmueble
from .InmuebleVivienda import InmuebleVivienda
from .Casa import Casa
from .Apartamento import Apartamento
from .CasaRural import CasaRural
from .CasaUrbana import CasaUrbana
from .ApartamentoFamiliar import ApartamentoFamiliar
from .Apartaestudio import Apartaestudio
from .CasaConjuntoCerrado import CasaConjuntoCerrado
from .CasaIndependiente import CasaIndependiente
from .Local import Local,TipoLocal
from .LocalComercial import LocalComercial
from .Oficina import Oficina